### ISSUE TITLE
TomlParser fails to parse the examples of the specification

### ISSUE THREAD

**Issue by guai** [TheElectronWill/Night-Config#12]
```toml
str5 = """
The quick brown \


  fox jumps over \
    the lazy dog."""

str6 = """\
       The quick brown \
       fox jumps over \
       the lazy dog.\
       """

data = [ ["gamma", "delta"], [1, 2] ]

arr3 = [ [ 1, 2 ], [3, 4, 5] ]

int5 = 1_000
int6 = 5_349_221
int7 = 1_2_3_4_5     # VALID but discouraged

flt8 = 9_224_617.445_991_228_313

[ d.e.f ]          # same as [d.e.f]
[ g .  h  . i ]    # same as [g.h.i]
[ j . "ʞ" . 'l' ]  # same as [j."ʞ".'l']



[[fruit]]
  name = "apple"

  [fruit.physical]
    color = "red"
    shape = "round"

  [[fruit.variety]]
    name = "red delicious"

  [[fruit.variety]]
    name = "granny smith"

[[fruit]]
  name = "banana"

  [[fruit.variety]]
    name = "plantain"
```
according to current toml readme this should also work, but it does not

**Comment by guai** [comment]
tested against 3337c1ff361f73755e3be0628daf1a565d3b2e44 master branch

**Comment by TheElectronWill** [comment]
What error do you get?

**Comment by guai** [comment]
```
com.electronwill.nightconfig.core.io.ParsingException: Invalid escapement: \
	at com.electronwill.nightconfig.toml.StringParser.escape(StringParser.java:135)
	at com.electronwill.nightconfig.toml.StringParser.parseMultiBasic(StringParser.java:70)
	at com.electronwill.nightconfig.toml.ValueParser.parse(ValueParser.java:39)
	at com.electronwill.nightconfig.toml.ValueParser.parse(ValueParser.java:57)
	at com.electronwill.nightconfig.toml.TableParser.parseNormal(TableParser.java:55)
	at com.electronwill.nightconfig.toml.TomlParser.parse(TomlParser.java:36)
	at com.electronwill.nightconfig.toml.TomlParser.parse(TomlParser.java:27)
	at com.electronwill.nightconfig.toml.TomlParser.parse(TomlParser.java:19)
	at com.electronwill.nightconfig.core.io.ConfigParser.parse(ConfigParser.java:78)
```
for \ inside triple quoted string

```
com.electronwill.nightconfig.core.io.ParsingException: Invalid value: 2]
	at com.electronwill.nightconfig.core.io.Utils.parseLong(Utils.java:69)
	at com.electronwill.nightconfig.toml.ValueParser.parseNumber(ValueParser.java:77)
	at com.electronwill.nightconfig.toml.ValueParser.parseNumberOrDateTime(ValueParser.java:65)
	at com.electronwill.nightconfig.toml.ValueParser.parse(ValueParser.java:52)
	at com.electronwill.nightconfig.toml.ArrayParser.parse(ArrayParser.java:23)
	at com.electronwill.nightconfig.toml.ValueParser.parse(ValueParser.java:29)
	at com.electronwill.nightconfig.toml.ArrayParser.parse(ArrayParser.java:23)
	at com.electronwill.nightconfig.toml.ValueParser.parse(ValueParser.java:29)
	at com.electronwill.nightconfig.toml.ValueParser.parse(ValueParser.java:57)
	at com.electronwill.nightconfig.toml.TableParser.parseNormal(TableParser.java:55)
	at com.electronwill.nightconfig.toml.TomlParser.parse(TomlParser.java:36)
	at com.electronwill.nightconfig.toml.TomlParser.parse(TomlParser.java:27)
	at com.electronwill.nightconfig.toml.TomlParser.parse(TomlParser.java:19)
	at com.electronwill.nightconfig.core.io.ConfigParser.parse(ConfigParser.java:78)
```
for inline array

```
com.electronwill.nightconfig.core.io.ParsingException: Invalid value: 1_000
	at com.electronwill.nightconfig.core.io.Utils.parseLong(Utils.java:69)
	at com.electronwill.nightconfig.toml.ValueParser.parseNumber(ValueParser.java:77)
	at com.electronwill.nightconfig.toml.ValueParser.parseNumberOrDateTime(ValueParser.java:65)
	at com.electronwill.nightconfig.toml.ValueParser.parse(ValueParser.java:52)
	at com.electronwill.nightconfig.toml.ValueParser.parse(ValueParser.java:57)
	at com.electronwill.nightconfig.toml.TableParser.parseNormal(TableParser.java:55)
	at com.electronwill.nightconfig.toml.TomlParser.parse(TomlParser.java:36)
	at com.electronwill.nightconfig.toml.TomlParser.parse(TomlParser.java:27)
	at com.electronwill.nightconfig.toml.TomlParser.parse(TomlParser.java:19)
	at com.electronwill.nightconfig.core.io.ConfigParser.parse(ConfigParser.java:78)
```
for _ inside number

```com.electronwill.nightconfig.core.io.ParsingException: Forbidden character in bare key: ' '
	at com.electronwill.nightconfig.toml.TableParser.parseKey(TableParser.java:139)
	at com.electronwill.nightconfig.toml.TableParser.parseTableName(TableParser.java:103)
	at com.electronwill.nightconfig.toml.TomlParser.parse(TomlParser.java:50)
	at com.electronwill.nightconfig.toml.TomlParser.parse(TomlParser.java:27)
	at com.electronwill.nightconfig.toml.TomlParser.parse(TomlParser.java:19)
	at com.electronwill.nightconfig.core.io.ConfigParser.parse(ConfigParser.java:78)
```
for space inside brackets

and
```
java.lang.IllegalArgumentException: Cannot add an element to an intermediary value of type: class java.util.ArrayList
	at com.electronwill.nightconfig.core.MapConfig.setValue(MapConfig.java:60)
	at com.electronwill.nightconfig.toml.TomlParser.parse(TomlParser.java:77)
	at com.electronwill.nightconfig.toml.TomlParser.parse(TomlParser.java:27)
	at com.electronwill.nightconfig.toml.TomlParser.parse(TomlParser.java:19)
	at com.electronwill.nightconfig.core.io.ConfigParser.parse(ConfigParser.java:78)
```
for fruit

**Comment by TheElectronWill** [comment]
I've created different issues so I can work on them separately.

**Comment by TheElectronWill** [comment]
The new test file seems to be parsed correctly now:
```toml
string = "value"
integer = 2
long = 1234567890000
double = 1.2345678901
spaces = 10_000_999.01_02_03 # this is valid!
bool_array = [true, false, true, false,] # comment
int_array = [0, 2]
nested_arrays = [ [1], [true, false], ['a', "b"]]

basicMultiline = """
First line
\tSecond line_\
       Still second line"""
literalMultiline= '''
First line
Second line'''

[table] #comment
    'key' = '"literal string"\n\t'
[table.subTable.subDefinedFirst]
    test = 'this is valid TOML'
[table.subTable]
    "subkey"=2017-02-25T12:00:01.123456789
    date=2017-04-04
    time=16:41:20
    preciseTime=16:41:20.00700

[[  array  .  ofTables  ]]
    a = false
[[array.ofTables]]
    a = [,]# This is an empty array
[[array.ofTables]]
    a = true

[[fruit]]
  name = "apple"

  [fruit.physical]
    color = "red"
    shape = "round"

  [[fruit.variety]]
    name = "red delicious"

  [[fruit.variety]]
    name = "granny smith"

[[fruit]]
  name = "banana"

  [[fruit.variety]]
    name = "plantain"
```

**Comment by guai** [comment]
I've just tried once again. Everything is fine except escaped whitespace inside triple quotes.
Latest master. commit 29d841915a1e7091419121dc353ad1435209452b
```toml
str5 = """
The quick brown \


  fox jumps over \
    the lazy dog."""

str6 = """\
       The quick brown \
       fox jumps over \
       the lazy dog.\
       """
```
still causes
```
com.electronwill.nightconfig.core.io.ParsingException: Invalid escapement: \
	at com.electronwill.nightconfig.toml.StringParser.escape(StringParser.java:136)
	at com.electronwill.nightconfig.toml.StringParser.parseMultiBasic(StringParser.java:71)
	at com.electronwill.nightconfig.toml.ValueParser.parse(ValueParser.java:39)
	at com.electronwill.nightconfig.toml.ValueParser.parse(ValueParser.java:57)
	at com.electronwill.nightconfig.toml.TableParser.parseNormal(TableParser.java:56)
	at com.electronwill.nightconfig.toml.TomlParser.parse(TomlParser.java:36)
	at com.electronwill.nightconfig.toml.TomlParser.parse(TomlParser.java:27)
	at com.electronwill.nightconfig.toml.TomlParser.parse(TomlParser.java:19)
	at com.electronwill.nightconfig.core.io.ConfigParser.parse(ConfigParser.java:78)
```

**Comment by TheElectronWill** [comment]
It works for me. Maybe it's a problem with newlines. Are you on windows?

**Comment by TheElectronWill** [comment]
I confirm that the problem is because of a bad handling of windows newlines in the multiline string parser.

**Comment by guai** [comment]
@TheElectronWill, yes. I'm under win 10

**Comment by guai** [comment]
Checked once again - works! Thanks a lot!
