### ISSUE TITLE
 Am I doing something wrong?

### ISSUE THREAD

**Issue by mani1232** [TheElectronWill/night-config#122]
What have I done wrong?

https://github.com/mani1232/CustomBot/blob/dev/src/main/java/ua/mani123/discord/discordUtils.java#L16

Exception in thread "main" java.lang.ClassCastException: class com.electronwill.nightconfig.core.SimpleCommentedConfig cannot be cast to class java.util.List (com.electronwill.nightconfig.core.SimpleCommentedConfig is in unnamed module of loader 'app'; java.util.List is in module java.base of loader 'bootstrap')
        at ua.mani123.discord.discordUtils.initBots(discordUtils.java:16)
        at ua.mani123.CBot.main(CBot.java:21)

**Comment by TheElectronWill** [comment]
What is your config file?

**Comment by mani1232** [comment]
https://github.com/mani1232/CustomBot/blob/dev/src/main/resources/config.toml

**Comment by mani1232** [comment]
lol i need to use [[text]] instead of [text]
