### ISSUE TITLE
NoFormatFound exception

### ISSUE THREAD

**Issue by MrEmmet66** [TheElectronWill/night-config#157]
Hi, i want to specify config in my resource folder. 
I have this lines:
```
        FileConfig config = FileConfig.builder("mobConfig.json").defaultResource("/resource/config.json").defaultData(new File("config/mobConfig.json")).build();
        config.load();
        System.out.println(Optional.ofNullable(config.get("minecraft:zombie")));
```
And i get NoFormatFound exception.
```
Caused by: com.electronwill.nightconfig.core.file.NoFormatFoundException: No suitable format for mobConfig.json
	at com.electronwill.nightconfig.core.file.FileConfig.builder(FileConfig.java:232)
	at com.electronwill.nightconfig.core.file.FileConfig.builder(FileConfig.java:258)
	at org.mbf.dimensiontags.DimensionTags.onInitialize(DimensionTags.java:69)
```

**Comment by MrEmmet66** [comment]
Oh, really, it worked. Sorry, thx
