### ISSUE TITLE
TomlParser doesn't handle nested array of tables

### ISSUE THREAD

**Issue by TheElectronWill** [TheElectronWill/Night-Config#17]
(reported by guai in [issue 12](https://github.com/TheElectronWill/Night-Config/issues/12))
This toml example throws an error:
```toml
[[fruit]]
  name = "apple"

  [fruit.physical]
    color = "red"
    shape = "round"

  [[fruit.variety]]
    name = "red delicious"

  [[fruit.variety]]
    name = "granny smith"

[[fruit]]
  name = "banana"

  [[fruit.variety]]
    name = "plantain"
```

```java
java.lang.IllegalArgumentException: Cannot add an element to an intermediary value of type: class java.util.ArrayList
	at com.electronwill.nightconfig.core.MapConfig.setValue(MapConfig.java:60)
	at com.electronwill.nightconfig.toml.TomlParser.parse(TomlParser.java:77)
	at com.electronwill.nightconfig.toml.TomlParser.parse(TomlParser.java:27)
	at com.electronwill.nightconfig.toml.TomlParser.parse(TomlParser.java:19)
	at com.electronwill.nightconfig.core.io.ConfigParser.parse(ConfigParser.java:78)
```

**Comment by TheElectronWill** [comment]
This bug is a bit longer to fix than the others ^_^
When trying to save a table, the parser should open any array of tables it encounters and use its last element. (of course it doesn not, for now) 
I will rethink my algorithms this weekend.

**Comment by TheElectronWill** [comment]
Allright, I've got a fix :-)
