### ISSUE TITLE
NoFormatFoundException on every file

### ISSUE THREAD

**Issue by lparolari** [TheElectronWill/Night-Config#33]
Hi,

i was using this library for some simple configuration handle, but i'm stucked with this problem:

this code
```
FileConfig config = FileConfig.of("config.json");
// FileConfig config = FileConfig.of("config.toml"); // like above
// FileConfig config = FileConfig.builder("config.json").build(); // has the same behaviour
```
always throws this exception
```
Exception in thread "main" com.electronwill.nightconfig.core.file.NoFormatFoundException: No suitable format for config.json
	at com.electronwill.nightconfig.core.file.FileConfig.of(FileConfig.java:66)
	at com.electronwill.nightconfig.core.file.FileConfig.of(FileConfig.java:92)
	at it.bcv.invade.appdb.Main.cfgTest(Main.java:83)
	at it.bcv.invade.appdb.Main.doMain(Main.java:33)
	at it.bcv.invade.appdb.Main.main(Main.java:25)
```
for every  file and/or extension given.
I've tried to copy some json/toml examples from github, however i got this error.

What i'm doing wrong? 

Thanks in advance!

**Comment by TheElectronWill** [comment]
Hi!
Have you declared the module of the language you want to use (json, toml, etc.) as a dependency, in addition to the core module?

**Comment by lparolari** [comment]
I've added this
```
<dependency>
    <groupId>com.github.TheElectronWill.Night-Config</groupId>
    <artifactId>json</artifactId>
    <version>3.0.4</version>
</dependency>
```
and now works like a charm.

I thought that the only import was this one at [https://jitpack.io/#TheElectronWill/Night-Config](https://jitpack.io/#TheElectronWill/Night-Config)...

Thanks a lot!
