### ISSUE TITLE
Unexpected ParsingException when using autoreload + autosave

### ISSUE THREAD

**Issue by lparolari** [TheElectronWill/Night-Config#36]
Hello,

I'm me, again.

I've encountered this following problem while executing sequential write (seconds of delay)...

- i have defined:

```
config = FileConfig.builder(configFile,JsonFormat.fancyInstance())
                .sync()
                .autosave()
                .autoreload()
                .build();

public <T> T get(String k, T def) {
    Log.debug("get");
    T x = config.get(k);
    return x != null ? x : def;
}

public <T> T put(String k, T v) {
    Log.debug("put");
    return config.set(k,v);
}
```

- i was doing some test and the problem was:
```
*** MAIN ***
// option 4 perform a read to a key
// option 5 write a random number on the same key

[ 4: read conf test, 5: write conf test ] ? chose: 4
[main] DEBUG it.bcv.invade.appdb.Configuration - get
97

[ 4: read conf test, 5: write conf test ] ? chose: 5
[main] DEBUG it.bcv.invade.appdb.Configuration - put

[ 4: read conf test, 5: write conf test ] ? chose: 5
[main] DEBUG it.bcv.invade.appdb.Configuration - put

[ 4: read conf test, 5: write conf test ] ? chose: 5
[main] DEBUG it.bcv.invade.appdb.Configuration - put

[ 4: read conf test, 5: write conf test ] ? chose: 5
[main] DEBUG it.bcv.invade.appdb.Configuration - put

[ 4: read conf test, 5: write conf test ] ? chose: 5
[main] DEBUG it.bcv.invade.appdb.Configuration - put

[ 4: read conf test, 5: write conf test ] ? chose: 5
[main] DEBUG it.bcv.invade.appdb.Configuration - put
Exception in thread "Thread-0" com.electronwill.nightconfig.core.io.ParsingException: Not enough data available
	at com.electronwill.nightconfig.core.io.ParsingException.notEnoughData(ParsingException.java:22)
	at com.electronwill.nightconfig.core.io.ReaderInput.directReadChar(ReaderInput.java:36)
	at com.electronwill.nightconfig.core.io.AbstractInput.readChar(AbstractInput.java:49)
	at com.electronwill.nightconfig.core.io.CharacterInput.readCharAndSkip(CharacterInput.java:59)
	at com.electronwill.nightconfig.json.JsonParser.parse(JsonParser.java:78)
	at com.electronwill.nightconfig.core.io.ConfigParser.parse(ConfigParser.java:149)
	at com.electronwill.nightconfig.core.io.ConfigParser.parse(ConfigParser.java:165)
	at com.electronwill.nightconfig.core.file.WriteSyncFileConfig.load(WriteSyncFileConfig.java:58)
	at com.electronwill.nightconfig.core.file.FileWatcher$WatcherThread.run(FileWatcher.java:174)

[ 4: read conf test, 5: write conf test ] ? chose: 
```

**what is** this exception? And why thrown only after a few writes? Should I **catch** it or i'm doing something wrong?

Thanks in advance!

**Comment by TheElectronWill** [comment]
`ParsingException: Not enough data available` is thrown when the parser misses some data, for instance when the JSON file is empty.

I've done some testing and it seems that, sometimes, the `FileWatcher` reloads the configuration before it has been completely written (this happens with `async` config too!). Then the `JsonParser` tries to parse an empty file and fails. Clearly it's a concurrency bug caused by overlapping reads and writes.

Regarding the exception, you should not catch it *in that case*. In other cases it can be fine to catch `ParsingException` and to tell the user that his configuration is invalid.

**Comment by TheElectronWill** [comment]
Allright, according to the test it should work from now on. Tell me if you've got the same problem again.
Thanks for reporting!

**Comment by lparolari** [comment]
Thanks a lot for the fix!
