### ISSUE TITLE
TOML ValueWriter breaks on Float

### ISSUE THREAD

**Issue by ichttt** [TheElectronWill/Night-Config#60]
Hi,
I use the new forge config system, which is build on night-config and it's toml module.
It seems like your ValueWriter does not work with `Float` values, as it tries to cast a `Float` to a `Double` implicitly when doing a `(double)` cast on a `Float`.
The line in question is https://github.com/TheElectronWill/Night-Config/blob/dddb3c0dabf997ce0a096b7425e670aa80905b81/toml/src/main/java/com/electronwill/nightconfig/toml/ValueWriter.java#L45
The exception is 
```
java.lang.ClassCastException: java.lang.Float cannot be cast to java.lang.Double
	at com.electronwill.nightconfig.toml.ValueWriter.write(ValueWriter.java:41)
	at com.electronwill.nightconfig.toml.ArrayWriter.write(ArrayWriter.java:34)
	at com.electronwill.nightconfig.toml.ValueWriter.write(ValueWriter.java:29)
	at com.electronwill.nightconfig.toml.TableWriter.writeNormal(TableWriter.java:72)
	at com.electronwill.nightconfig.toml.TableWriter.writeNormal(TableWriter.java:43)
```
...
Thanks a lot in advance!

**Comment by TheElectronWill** [comment]
Fixed in 3.5.2 which is being released. Thanks for reporting the bug :)
