### ISSUE TITLE
De serializing a Map results in a Null pointer ex

### ISSUE THREAD

**Issue by NeumimTo** [TheElectronWill/night-config#70]
```
class A {
    @Path("a")
    Map<String, String> map;
}
```

```
a: {
   "b": "C"
}
```

throws 

```
java.lang.NullPointerException
	at com.electronwill.nightconfig.core.conversion.ObjectConverter.convertToObject(ObjectConverter.java:202)
	at com.electronwill.nightconfig.core.conversion.ObjectConverter.convertToObject(ObjectConverter.java:239)
	at com.electronwill.nightconfig.core.conversion.ObjectConverter.toObject(ObjectConverter.java:101)
	at com.electronwill.nightconfig.core.conversion.ObjectConverter.toObject(ObjectConverter.java:114)

```

```
	while (clazz != Object.class) {
                 .....
		 clazz = clazz.getSuperclass();
         }
 
```

all java interfaces return null here, but i assume that the bug lies elsewhere, as the library is able to deserialize field with types such as List and Set

**Comment by TheElectronWill** [comment]
Collections benefit from a custom logic, so the bug exists for every other interface.
Thanks for reporting! I'll fix it for the next release.

Meanwhile, you can replace the map by a `Config` and use its `valueMap()`.
