### ISSUE TITLE
TomlWriter crashes on Android API 23

### ISSUE THREAD

**Issue by sunsunich** [TheElectronWill/night-config#72]
Dear Author,

Thank you very much for creating night-config.

I am trying to use night-config on embedded Android device with Android API 23. We cannot update the API level due to the hardware limitations.

I am using toml_android:3.6.0 library:
```
    implementation 'com.electronwill.night-config:toml_android:3.6.0'
    implementation 'com.electronwill.night-config:json_android:3.6.0'
```
The issue also reproduces on the latest 3.6.2

My application crashes with the following runtime error:
```
2-04 11:05:47.713 7486-7486/com....: PT0.663S ...: java.lang.NoClassDefFoundError: com.electronwill.nightconfig.toml.-$$Lambda$W6hkGRDrhNSgPidfrf37K2zYOZA
        at com.electronwill.nightconfig.toml.TomlWriter.<init>(TomlWriter.java:18)
        at com.electronwill.nightconfig.toml.TomlFormat.createWriter(TomlFormat.java:53)
        at com.electronwill.nightconfig.toml.TomlFormat.createWriter(TomlFormat.java:14)
        at com.electronwill.nightconfig.core.file.GenericBuilder.<init>(GenericBuilder.java:50)
        at com.electronwill.nightconfig.core.file.FileConfigBuilder.<init>(FileConfigBuilder.java:30)
        at com.electronwill.nightconfig.core.file.FileConfig$-CC.builder(FileConfig.java:170)
        at com.electronwill.nightconfig.core.file.FileConfig$-CC.of(FileConfig.java:71)
        at com.electronwill.nightconfig.core.file.FileConfig$-CC.of(FileConfig.java:60)
        at com.....TomlConfigDataProvider.getConfigurationData(TomlConfigDataProvider.java:84)
```
The code I execute in my TomlConfigDataProvider:
`FileConfig config = FileConfig.of(tomlFile);`

I assume the issue is happening because of this line in TomlWriter:
```
private Predicate<UnmodifiableConfig> writeTableInlinePredicate = UnmodifiableConfig::isEmpty;
```

You are using Predicate from java.util.function.Predicate, which does not exist in Android API 23.
However, you have your own version of Predicate:
`com.electronwill.nightconfig.core.utils.Predicate`

I think the issue would be resolved if you replaced the import in TomlWriter.

Could you please make this change to night-config and make sure FileConfig.of(..) works on older versions of Android?

Thank you very much in advance!

Best regards,
Alexander

**Comment by TheElectronWill** [comment]
Hello! Thank you for reporting this problem. Indeed, the android version of `TomlWriter` should use my version of `Predicate` instead of the standard Java 8 one. This will be fixed in the next version.

**Comment by TheElectronWill** [comment]
Closing for now.
Very old Android API versions are troublesome to support and I don't plan to maintain this in the near future...
