### ISSUE TITLE
TOML Example cannot be parsed

### ISSUE THREAD

**Issue by AriDeve** [TheElectronWill/night-config#93]
Date in the TOML example found at https://github.com/toml-lang/toml is not supported, as the time offset causes an error.

Exampe:
```
# This is a TOML document.

title = "TOML Example"

[owner]
name = "Tom Preston-Werner"
dob = 1979-05-27T07:32:00-08:00 # First class dates

[database]
server = "192.168.1.1"
ports = [ 8000, 8001, 8002 ]
connection_max = 5000
enabled = true

[servers]

  # Indentation (tabs and/or spaces) is allowed but not required
  [servers.alpha]
  ip = "10.0.0.1"
  dc = "eqdc10"

  [servers.beta]
  ip = "10.0.0.2"
  dc = "eqdc10"

[clients]
data = [ ["gamma", "delta"], [1, 2] ]

# Line breaks are OK when inside arrays
hosts = [
  "alpha",
  "omega"
]
```

Error:
```
java.time.DateTimeException: Invalid ID for ZoneOffset, non numeric characters found: -08:00
        at java.time.ZoneOffset.parseNumber(ZoneOffset.java:271) ~[?:?]
        at java.time.ZoneOffset.of(ZoneOffset.java:234) ~[?:?]
```

**Comment by TheElectronWill** [comment]
Fixed in dfbabf2c837c411250c6a6959c5abb4a7ee589be
