### ISSUE TITLE
1.18 cannot load any electronwill nightconfig mod

### ISSUE THREAD

**Issue by red2blue** [TheElectronWill/night-config#99]
Receiving this error on server start up for any mod that uses Nightconfig 

example;
```java

[19:50:48] [Forge Version Check/INFO]: [bigbrain] Starting version check at https://raw.githubusercontent.com/seymourimadeit/Big-Brain/main/update.json
[19:50:48] [Thread-0/FATAL]: Attempted to load class net/minecraft/client/Minecraft for invalid dist DEDICATED_SERVER
[19:50:48] [Thread-0/ERROR]: Exception caught during firing event: Attempted to load class net/minecraft/client/Minecraft for invalid dist DEDICATED_SERVER
	Index: 1
	Listeners:
		0: NORMAL
		1: net.minecraftforge.eventbus.EventBus$$Lambda$3720/0x00000008015e5710@19aea55
java.lang.RuntimeException: Attempted to load class net/minecraft/client/Minecraft for invalid dist DEDICATED_SERVER
	at MC-BOOTSTRAP/fmlloader@1.18-38.0.17/net.minecraftforge.fml.loading.RuntimeDistCleaner.processClassWithFlags(RuntimeDistCleaner.java:71)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.0.7/cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:88)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.0.7/cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:120)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.0.7/cpw.mods.modlauncher.TransformingClassLoader.maybeTransformClassBytes(TransformingClassLoader.java:50)
	at cpw.mods.securejarhandler@0.9.54/cpw.mods.cl.ModuleClassLoader.readerToClass(ModuleClassLoader.java:110)
	at cpw.mods.securejarhandler@0.9.54/cpw.mods.cl.ModuleClassLoader.lambda$findClass$16(ModuleClassLoader.java:213)
	at cpw.mods.securejarhandler@0.9.54/cpw.mods.cl.ModuleClassLoader.loadFromModule(ModuleClassLoader.java:223)
	at cpw.mods.securejarhandler@0.9.54/cpw.mods.cl.ModuleClassLoader.findClass(ModuleClassLoader.java:213)
	at cpw.mods.securejarhandler@0.9.54/cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:130)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at TRANSFORMER/balm@2.3.0+0/net.blay09.mods.balm.forge.config.ForgeBalmConfig.lambda$initializeBackingConfig$3(ForgeBalmConfig.java:149)
	at MC-BOOTSTRAP/eventbus@5.0.3/net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:247)
	at MC-BOOTSTRAP/eventbus@5.0.3/net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:239)
	at MC-BOOTSTRAP/eventbus@5.0.3/net.minecraftforge.eventbus.EventBus.post(EventBus.java:302)
	at MC-BOOTSTRAP/eventbus@5.0.3/net.minecraftforge.eventbus.EventBus.post(EventBus.java:283)
	at LAYER PLUGIN/javafmllanguage@1.18-38.0.17/net.minecraftforge.fml.javafmlmod.FMLModContainer.lambda$new$0(FMLModContainer.java:55)
	at LAYER PLUGIN/fmlcore@1.18-38.0.17/net.minecraftforge.fml.ModContainer.lambda$dispatchConfigEvent$7(ModContainer.java:149)
	at java.base/java.util.Optional.ifPresent(Optional.java:178)
	at LAYER PLUGIN/fmlcore@1.18-38.0.17/net.minecraftforge.fml.ModContainer.dispatchConfigEvent(ModContainer.java:149)
	at LAYER PLUGIN/fmlcore@1.18-38.0.17/net.minecraftforge.fml.config.ModConfig.fireEvent(ModConfig.java:90)
	at LAYER PLUGIN/fmlcore@1.18-38.0.17/net.minecraftforge.fml.config.ConfigFileTypeHandler$ConfigWatcher.run(ConfigFileTypeHandler.java:160)
	at MC-BOOTSTRAP/com.electronwill.nightconfig.core@3.6.4/com.electronwill.nightconfig.core.file.FileWatcher$WatcherThread.run(FileWatcher.java:181)

[19:50:48] [Thread-0/FATAL]: Attempted to load class net/minecraft/client/Minecraft for invalid dist DEDICATED_SERVER
[19:50:48] [Thread-0/ERROR]: Exception caught during firing event: Attempted to load class net/minecraft/client/Minecraft for invalid dist DEDICATED_SERVER
	Index: 1
	Listeners:
		0: NORMAL
		1: net.minecraftforge.eventbus.EventBus$$Lambda$3720/0x00000008015e5710@2d0a183d
java.lang.RuntimeException: Attempted to load class net/minecraft/client/Minecraft for invalid dist DEDICATED_SERVER
	at MC-BOOTSTRAP/fmlloader@1.18-38.0.17/net.minecraftforge.fml.loading.RuntimeDistCleaner.processClassWithFlags(RuntimeDistCleaner.java:71)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.0.7/cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:88)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.0.7/cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:120)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.0.7/cpw.mods.modlauncher.TransformingClassLoader.maybeTransformClassBytes(TransformingClassLoader.java:50)
	at cpw.mods.securejarhandler@0.9.54/cpw.mods.cl.ModuleClassLoader.readerToClass(ModuleClassLoader.java:110)
	at cpw.mods.securejarhandler@0.9.54/cpw.mods.cl.ModuleClassLoader.lambda$findClass$16(ModuleClassLoader.java:213)
	at cpw.mods.securejarhandler@0.9.54/cpw.mods.cl.ModuleClassLoader.loadFromModule(ModuleClassLoader.java:223)
	at cpw.mods.securejarhandler@0.9.54/cpw.mods.cl.ModuleClassLoader.findClass(ModuleClassLoader.java:213)
	at cpw.mods.securejarhandler@0.9.54/cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:130)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at TRANSFORMER/balm@2.3.0+0/net.blay09.mods.balm.forge.config.ForgeBalmConfig.lambda$initializeBackingConfig$3(ForgeBalmConfig.java:149)
	at MC-BOOTSTRAP/eventbus@5.0.3/net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:247)
	at MC-BOOTSTRAP/eventbus@5.0.3/net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:239)
	at MC-BOOTSTRAP/eventbus@5.0.3/net.minecraftforge.eventbus.EventBus.post(EventBus.java:302)
	at MC-BOOTSTRAP/eventbus@5.0.3/net.minecraftforge.eventbus.EventBus.post(EventBus.java:283)
	at LAYER PLUGIN/javafmllanguage@1.18-38.0.17/net.minecraftforge.fml.javafmlmod.FMLModContainer.lambda$new$0(FMLModContainer.java:55)
	at LAYER PLUGIN/fmlcore@1.18-38.0.17/net.minecraftforge.fml.ModContainer.lambda$dispatchConfigEvent$7(ModContainer.java:149)
	at java.base/java.util.Optional.ifPresent(Optional.java:178)
	at LAYER PLUGIN/fmlcore@1.18-38.0.17/net.minecraftforge.fml.ModContainer.dispatchConfigEvent(ModContainer.java:149)
	at LAYER PLUGIN/fmlcore@1.18-38.0.17/net.minecraftforge.fml.config.ModConfig.fireEvent(ModConfig.java:90)
	at LAYER PLUGIN/fmlcore@1.18-38.0.17/net.minecraftforge.fml.config.ConfigFileTypeHandler$ConfigWatcher.run(ConfigFileTypeHandler.java:160)
	at MC-BOOTSTRAP/com.electronwill.nightconfig.core@3.6.4/com.electronwill.nightconfig.core.file.FileWatcher$WatcherThread.run(FileWatcher.java:181)

[19:50:48] [Thread-0/FATAL]: Attempted to load class net/minecraft/client/Minecraft for invalid dist DEDICATED_SERVER
[19:50:48] [Thread-0/ERROR]: Exception caught during firing event: Attempted to load class net/minecraft/client/Minecraft for invalid dist DEDICATED_SERVER
	Index: 1
	Listeners:
		0: NORMAL
		1: net.minecraftforge.eventbus.EventBus$$Lambda$3720/0x00000008015e5710@197ba43e
java.lang.RuntimeException: Attempted to load class net/minecraft/client/Minecraft for invalid dist DEDICATED_SERVER
	at MC-BOOTSTRAP/fmlloader@1.18-38.0.17/net.minecraftforge.fml.loading.RuntimeDistCleaner.processClassWithFlags(RuntimeDistCleaner.java:71)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.0.7/cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:88)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.0.7/cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:120)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.0.7/cpw.mods.modlauncher.TransformingClassLoader.maybeTransformClassBytes(TransformingClassLoader.java:50)
	at cpw.mods.securejarhandler@0.9.54/cpw.mods.cl.ModuleClassLoader.readerToClass(ModuleClassLoader.java:110)
	at cpw.mods.securejarhandler@0.9.54/cpw.mods.cl.ModuleClassLoader.lambda$findClass$16(ModuleClassLoader.java:213)
	at cpw.mods.securejarhandler@0.9.54/cpw.mods.cl.ModuleClassLoader.loadFromModule(ModuleClassLoader.java:223)
	at cpw.mods.securejarhandler@0.9.54/cpw.mods.cl.ModuleClassLoader.findClass(ModuleClassLoader.java:213)
	at cpw.mods.securejarhandler@0.9.54/cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:130)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at TRANSFORMER/balm@2.3.0+0/net.blay09.mods.balm.forge.config.ForgeBalmConfig.lambda$initializeBackingConfig$3(ForgeBalmConfig.java:149)
	at MC-BOOTSTRAP/eventbus@5.0.3/net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:247)
	at MC-BOOTSTRAP/eventbus@5.0.3/net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:239)
	at MC-BOOTSTRAP/eventbus@5.0.3/net.minecraftforge.eventbus.EventBus.post(EventBus.java:302)
	at MC-BOOTSTRAP/eventbus@5.0.3/net.minecraftforge.eventbus.EventBus.post(EventBus.java:283)
	at LAYER PLUGIN/javafmllanguage@1.18-38.0.17/net.minecraftforge.fml.javafmlmod.FMLModContainer.lambda$new$0(FMLModContainer.java:55)
	at LAYER PLUGIN/fmlcore@1.18-38.0.17/net.minecraftforge.fml.ModContainer.lambda$dispatchConfigEvent$7(ModContainer.java:149)
	at java.base/java.util.Optional.ifPresent(Optional.java:178)
	at LAYER PLUGIN/fmlcore@1.18-38.0.17/net.minecraftforge.fml.ModContainer.dispatchConfigEvent(ModContainer.java:149)
	at LAYER PLUGIN/fmlcore@1.18-38.0.17/net.minecraftforge.fml.config.ModConfig.fireEvent(ModConfig.java:90)
	at LAYER PLUGIN/fmlcore@1.18-38.0.17/net.minecraftforge.fml.config.ConfigFileTypeHandler$ConfigWatcher.run(ConfigFileTypeHandler.java:160)
	at MC-BOOTSTRAP/com.electronwill.nightconfig.core@3.6.4/com.electronwill.nightconfig.core.file.FileWatcher$WatcherThread.run(FileWatcher.java:181)

[19:50:48] [Thread-0/FATAL]: Attempted to load class net/minecraft/client/Minecraft for invalid dist DEDICATED_SERVER
[19:50:48] [Thread-0/ERROR]: Exception caught during firing event: Attempted to load class net/minecraft/client/Minecraft for invalid dist DEDICATED_SERVER
	Index: 1
	Listeners:
		0: NORMAL
		1: net.minecraftforge.eventbus.EventBus$$Lambda$3720/0x00000008015e5710@21cb1168
java.lang.RuntimeException: Attempted to load class net/minecraft/client/Minecraft for invalid dist DEDICATED_SERVER
	at MC-BOOTSTRAP/fmlloader@1.18-38.0.17/net.minecraftforge.fml.loading.RuntimeDistCleaner.processClassWithFlags(RuntimeDistCleaner.java:71)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.0.7/cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:88)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.0.7/cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:120)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.0.7/cpw.mods.modlauncher.TransformingClassLoader.maybeTransformClassBytes(TransformingClassLoader.java:50)
	at cpw.mods.securejarhandler@0.9.54/cpw.mods.cl.ModuleClassLoader.readerToClass(ModuleClassLoader.java:110)
	at cpw.mods.securejarhandler@0.9.54/cpw.mods.cl.ModuleClassLoader.lambda$findClass$16(ModuleClassLoader.java:213)
	at cpw.mods.securejarhandler@0.9.54/cpw.mods.cl.ModuleClassLoader.loadFromModule(ModuleClassLoader.java:223)
	at cpw.mods.securejarhandler@0.9.54/cpw.mods.cl.ModuleClassLoader.findClass(ModuleClassLoader.java:213)
	at cpw.mods.securejarhandler@0.9.54/cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:130)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at TRANSFORMER/balm@2.3.0+0/net.blay09.mods.balm.forge.config.ForgeBalmConfig.lambda$initializeBackingConfig$3(ForgeBalmConfig.java:149)
	at MC-BOOTSTRAP/eventbus@5.0.3/net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:247)
	at MC-BOOTSTRAP/eventbus@5.0.3/net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:239)
	at MC-BOOTSTRAP/eventbus@5.0.3/net.minecraftforge.eventbus.EventBus.post(EventBus.java:302)
	at MC-BOOTSTRAP/eventbus@5.0.3/net.minecraftforge.eventbus.EventBus.post(EventBus.java:283)
	at LAYER PLUGIN/javafmllanguage@1.18-38.0.17/net.minecraftforge.fml.javafmlmod.FMLModContainer.lambda$new$0(FMLModContainer.java:55)
	at LAYER PLUGIN/fmlcore@1.18-38.0.17/net.minecraftforge.fml.ModContainer.lambda$dispatchConfigEvent$7(ModContainer.java:149)
	at java.base/java.util.Optional.ifPresent(Optional.java:178)
	at LAYER PLUGIN/fmlcore@1.18-38.0.17/net.minecraftforge.fml.ModContainer.dispatchConfigEvent(ModContainer.java:149)
	at LAYER PLUGIN/fmlcore@1.18-38.0.17/net.minecraftforge.fml.config.ModConfig.fireEvent(ModConfig.java:90)
	at LAYER PLUGIN/fmlcore@1.18-38.0.17/net.minecraftforge.fml.config.ConfigFileTypeHandler$ConfigWatcher.run(ConfigFileTypeHandler.java:160)
	at MC-BOOTSTRAP/com.electronwill.nightconfig.core@3.6.4/com.electronwill.nightconfig.core.file.FileWatcher$WatcherThread.run(FileWatcher.java:181)

[19:50:48] [Thread-0/FATAL]: Attempted to load class net/minecraft/client/Minecraft for invalid dist DEDICATED_SERVER
[19:50:48] [Thread-0/ERROR]: Exception caught during firing event: Attempted to load class net/minecraft/client/Minecraft for invalid dist DEDICATED_SERVER
	Index: 1
	Listeners:
		0: NORMAL
		1: net.minecraftforge.eventbus.EventBus$$Lambda$3720/0x00000008015e5710@521abb3c
java.lang.RuntimeException: Attempted to load class net/minecraft/client/Minecraft for invalid dist DEDICATED_SERVER
	at MC-BOOTSTRAP/fmlloader@1.18-38.0.17/net.minecraftforge.fml.loading.RuntimeDistCleaner.processClassWithFlags(RuntimeDistCleaner.java:71)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.0.7/cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:88)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.0.7/cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:120)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.0.7/cpw.mods.modlauncher.TransformingClassLoader.maybeTransformClassBytes(TransformingClassLoader.java:50)
	at cpw.mods.securejarhandler@0.9.54/cpw.mods.cl.ModuleClassLoader.readerToClass(ModuleClassLoader.java:110)
	at cpw.mods.securejarhandler@0.9.54/cpw.mods.cl.ModuleClassLoader.lambda$findClass$16(ModuleClassLoader.java:213)
	at cpw.mods.securejarhandler@0.9.54/cpw.mods.cl.ModuleClassLoader.loadFromModule(ModuleClassLoader.java:223)
	at cpw.mods.securejarhandler@0.9.54/cpw.mods.cl.ModuleClassLoader.findClass(ModuleClassLoader.java:213)
	at cpw.mods.securejarhandler@0.9.54/cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:130)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at TRANSFORMER/balm@2.3.0+0/net.blay09.mods.balm.forge.config.ForgeBalmConfig.lambda$initializeBackingConfig$3(ForgeBalmConfig.java:149)
	at MC-BOOTSTRAP/eventbus@5.0.3/net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:247)
	at MC-BOOTSTRAP/eventbus@5.0.3/net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:239)
	at MC-BOOTSTRAP/eventbus@5.0.3/net.minecraftforge.eventbus.EventBus.post(EventBus.java:302)
	at MC-BOOTSTRAP/eventbus@5.0.3/net.minecraftforge.eventbus.EventBus.post(EventBus.java:283)
	at LAYER PLUGIN/javafmllanguage@1.18-38.0.17/net.minecraftforge.fml.javafmlmod.FMLModContainer.lambda$new$0(FMLModContainer.java:55)
	at LAYER PLUGIN/fmlcore@1.18-38.0.17/net.minecraftforge.fml.ModContainer.lambda$dispatchConfigEvent$7(ModContainer.java:149)
	at java.base/java.util.Optional.ifPresent(Optional.java:178)
	at LAYER PLUGIN/fmlcore@1.18-38.0.17/net.minecraftforge.fml.ModContainer.dispatchConfigEvent(ModContainer.java:149)
	at LAYER PLUGIN/fmlcore@1.18-38.0.17/net.minecraftforge.fml.config.ModConfig.fireEvent(ModConfig.java:90)
	at LAYER PLUGIN/fmlcore@1.18-38.0.17/net.minecraftforge.fml.config.ConfigFileTypeHandler$ConfigWatcher.run(ConfigFileTypeHandler.java:160)
	at MC-BOOTSTRAP/com.electronwill.nightconfig.core@3.6.4/com.electronwill.nightconfig.core.file.FileWatcher$WatcherThread.run(FileWatcher.java:181)
	```

**Comment by red2blue** [comment]
Heres another error from another mod dependant on Nightconfig for 1.18


```java
[19:50:46] [main/INFO]: Registering 20 structures of shrines Mod
[19:50:46] [Thread-0/FATAL]: Attempted to load class net/minecraft/client/Minecraft for invalid dist DEDICATED_SERVER
[19:50:46] [Thread-0/ERROR]: Exception caught during firing event: Attempted to load class net/minecraft/client/Minecraft for invalid dist DEDICATED_SERVER
	Index: 1
	Listeners:
		0: NORMAL
		1: net.minecraftforge.eventbus.EventBus$$Lambda$3720/0x00000008015e5710@5cbec4e6
java.lang.RuntimeException: Attempted to load class net/minecraft/client/Minecraft for invalid dist DEDICATED_SERVER
	at MC-BOOTSTRAP/fmlloader@1.18-38.0.17/net.minecraftforge.fml.loading.RuntimeDistCleaner.processClassWithFlags(RuntimeDistCleaner.java:71)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.0.7/cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:88)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.0.7/cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:120)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.0.7/cpw.mods.modlauncher.TransformingClassLoader.maybeTransformClassBytes(TransformingClassLoader.java:50)
	at cpw.mods.securejarhandler@0.9.54/cpw.mods.cl.ModuleClassLoader.readerToClass(ModuleClassLoader.java:110)
	at cpw.mods.securejarhandler@0.9.54/cpw.mods.cl.ModuleClassLoader.lambda$findClass$16(ModuleClassLoader.java:213)
	at cpw.mods.securejarhandler@0.9.54/cpw.mods.cl.ModuleClassLoader.loadFromModule(ModuleClassLoader.java:223)
	at cpw.mods.securejarhandler@0.9.54/cpw.mods.cl.ModuleClassLoader.findClass(ModuleClassLoader.java:213)
	at cpw.mods.securejarhandler@0.9.54/cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:130)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at TRANSFORMER/balm@2.3.0+0/net.blay09.mods.balm.forge.config.ForgeBalmConfig.lambda$initializeBackingConfig$3(ForgeBalmConfig.java:149)
	at MC-BOOTSTRAP/eventbus@5.0.3/net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:247)
	at MC-BOOTSTRAP/eventbus@5.0.3/net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:239)
	at MC-BOOTSTRAP/eventbus@5.0.3/net.minecraftforge.eventbus.EventBus.post(EventBus.java:302)
	at MC-BOOTSTRAP/eventbus@5.0.3/net.minecraftforge.eventbus.EventBus.post(EventBus.java:283)
	at LAYER PLUGIN/javafmllanguage@1.18-38.0.17/net.minecraftforge.fml.javafmlmod.FMLModContainer.lambda$new$0(FMLModContainer.java:55)
	at LAYER PLUGIN/fmlcore@1.18-38.0.17/net.minecraftforge.fml.ModContainer.lambda$dispatchConfigEvent$7(ModContainer.java:149)
	at java.base/java.util.Optional.ifPresent(Optional.java:178)
	at LAYER PLUGIN/fmlcore@1.18-38.0.17/net.minecraftforge.fml.ModContainer.dispatchConfigEvent(ModContainer.java:149)
	at LAYER PLUGIN/fmlcore@1.18-38.0.17/net.minecraftforge.fml.config.ModConfig.fireEvent(ModConfig.java:90)
	at LAYER PLUGIN/fmlcore@1.18-38.0.17/net.minecraftforge.fml.config.ConfigFileTypeHandler$ConfigWatcher.run(ConfigFileTypeHandler.java:160)
	at MC-BOOTSTRAP/com.electronwill.
```

**Comment by sciwhiz12** [comment]
This doesn't seem like a NightConfig problem but more a problem with the Minecraft mod `balm` mentioned in the stacktraces. Bring the stacktraces to the developer of that mod instead to fix their problem (which seems to be the improper reference of the `Minecraft` client-only class in common code, which leads to a crash on the dedicated server).

**Comment by TheElectronWill** [comment]
NightConfig is included in Forge, that's why it can show up in many stacktraces. However I agree with the comment above: the root of the problem does not seem to be NightConfig itself.

Are you trying to install a client-only mod on a server?

**Comment by red2blue** [comment]
There were about 5 mods that I was crashing due to being on the server, most client mods, but what makes no sense is that one was a client<>server side both, Enhancing Farming, that was crashing with the same message. I'll report it to them as well. Thank you guys for the information, I will bring this to Balm.
